### ISSUE TITLE
GIF/Video of piglin crafting armor is too large (`Content length exceeded` error)

### ISSUE THREAD

**Issue by James103** [GStefanowich/MC-Nether-Mod#3]
One of the images in the README points to the following URL:
```
https://camo.githubusercontent.com/50e6e2525bfc10bff5cade25240d7ddf439e24ce9727be3828588a7d437c79f6/68747470733a2f2f692e696d6775722e636f6d2f314676493636472e676966
```

Since the GIF/video hosted at that URL is bigger than the maximum permitted size of GitHub images (a couple of megabytes), attempting to access this errors out with the error `Content length exceeded`.

A version of this video is also hosted at https://i.imgur.com/1FvI66G.mp4, so the link should be changed to that if possible.

**Comment by GStefanowich** [comment]
GitHubs user-content CDN doesn't seem to support MP4 extension types. Changing that results in the error `Non-Image content-type returned` instead of `Content length exceeded`. I wasn't too worried about changing it, the `README.md` is a pretty close copy of [the CurseForge page](https://www.curseforge.com/minecraft/mc-mods/piglin-tweaks-mod) where the image is loaded directly through imgur.

**Comment by James103** [comment]
Closing because the issue is not feasible to fix given the current infrastructure. It is still present, just can't be fixed without changes in Github's end.
